### ISSUE TITLE
Missing puzzle calibration file

### ISSUE THREAD

**Issue by pv33** [ivapylibs/Surveillance#13]
Cannot run ``rosbag_runner`` because calibration file is missing.  Please check file dependencies of the python test file and make sure they are in the dropbox.

**Comment by yiyeChen** [comment]
Just pushed that file

**Comment by pv33** [comment]
Belongs in dropbox.  Deleted from repo and adding there.

**Comment by yiyeChen** [comment]
Updated. It is [here](https://www.dropbox.com/s/qurvcfmxdlpoy8h/caliSolBoard.obj?dl=0)
