### ISSUE TITLE
Hand Tracking - Tests and Validation

### ISSUE THREAD

**Issue by pv33** [ivapylibs/Surveillance#25]
Hand tracking is not only the segmentation but the track pointer. The runner does not display the track point. I am not even sure what test script does.  Please provide information about these points in the response.

Please explain here what is needed for that to happen.

I see some code in surveillance/testing, but it is for the core parts alone and don't seem to reflect current usage.
Please indicate where scripts are that test it out and can run without problems based on current codebase.

If they don't exist, please respond simply with that statement, then explain what is needed to get such a testing script working.  In principle a lot of the heavy lifting should be done by the classes and not in the script.

**Comment by yiyeChen** [comment]
The original ``rosbag_runner`` involves such functionality, but as it evolves, I think some functionalities are gone. So now it does not exist.

To add such a function, just use the opencv to plot the ``Base.hTracker`` member on the image. This member already stores the coordinates of the hand tracker. The opencv command is ``cv2.circle``. 

I think I can add this easily if needed.

**Comment by pv33** [comment]
Do it right. Encapsulate please.

**Comment by yiyeChen** [comment]
Encapsulated. See the #28 .
