### ISSUE TITLE
Height estimation class - put somewhere else

### ISSUE THREAD

**Issue by yiyeChen** [ivapylibs/Surveillance#3]
The height estimation code is put here temporarily. Needs to create a new depth processing repository or sensor signal processing repository and transfer the code there.

Will do that when such a new repository is designed

**Comment by pv33** [comment]
Code base changed such that this is not relevant. There are a couple ways to do this that are in the Detector package of ivapy libraries. Used best version (not truly best but best of what options we have) in Mary perception ROS package.
